/* eslint-disable */
// Generated by Wrangler — see wrangler.jsonc for binding configuration

/// <reference types="@cloudflare/workers-types" />

declare namespace Cloudflare {
	interface Env {
		STORAGE: R2Bucket;
		DB: D1Database;
		ASSETS: Fetcher;
		CLOUDFLARE_ACCOUNT_ID: string;
		CLOUDFLARE_DATABASE_ID: string;
		CLOUDFLARE_D1_TOKEN: string;
	}
}
interface Env extends Cloudflare.Env {}
